/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegulamentRouteImport } from './routes/regulament'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as CodPenalRouteImport } from './routes/cod-penal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumForumSlugRouteImport } from './routes/forum.$forumSlug'
import { Route as ForumThreadThreadIdRouteImport } from './routes/forum.thread.$threadId'
import { Route as ForumNewTopicForumSlugRouteImport } from './routes/forum.new-topic.$forumSlug'

const RegulamentRoute = RegulamentRouteImport.update({
  id: '/regulament',
  path: '/regulament',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const CodPenalRoute = CodPenalRouteImport.update({
  id: '/cod-penal',
  path: '/cod-penal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumSlugRoute = ForumForumSlugRouteImport.update({
  id: '/$forumSlug',
  path: '/$forumSlug',
  getParentRoute: () => ForumRoute,
} as any)
const ForumThreadThreadIdRoute = ForumThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => ForumRoute,
} as any)
const ForumNewTopicForumSlugRoute = ForumNewTopicForumSlugRouteImport.update({
  id: '/new-topic/$forumSlug',
  path: '/new-topic/$forumSlug',
  getParentRoute: () => ForumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cod-penal': typeof CodPenalRoute
  '/forum': typeof ForumRouteWithChildren
  '/regulament': typeof RegulamentRoute
  '/forum/$forumSlug': typeof ForumForumSlugRoute
  '/forum/new-topic/$forumSlug': typeof ForumNewTopicForumSlugRoute
  '/forum/thread/$threadId': typeof ForumThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cod-penal': typeof CodPenalRoute
  '/forum': typeof ForumRouteWithChildren
  '/regulament': typeof RegulamentRoute
  '/forum/$forumSlug': typeof ForumForumSlugRoute
  '/forum/new-topic/$forumSlug': typeof ForumNewTopicForumSlugRoute
  '/forum/thread/$threadId': typeof ForumThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cod-penal': typeof CodPenalRoute
  '/forum': typeof ForumRouteWithChildren
  '/regulament': typeof RegulamentRoute
  '/forum/$forumSlug': typeof ForumForumSlugRoute
  '/forum/new-topic/$forumSlug': typeof ForumNewTopicForumSlugRoute
  '/forum/thread/$threadId': typeof ForumThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cod-penal'
    | '/forum'
    | '/regulament'
    | '/forum/$forumSlug'
    | '/forum/new-topic/$forumSlug'
    | '/forum/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cod-penal'
    | '/forum'
    | '/regulament'
    | '/forum/$forumSlug'
    | '/forum/new-topic/$forumSlug'
    | '/forum/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cod-penal'
    | '/forum'
    | '/regulament'
    | '/forum/$forumSlug'
    | '/forum/new-topic/$forumSlug'
    | '/forum/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CodPenalRoute: typeof CodPenalRoute
  ForumRoute: typeof ForumRouteWithChildren
  RegulamentRoute: typeof RegulamentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regulament': {
      id: '/regulament'
      path: '/regulament'
      fullPath: '/regulament'
      preLoaderRoute: typeof RegulamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cod-penal': {
      id: '/cod-penal'
      path: '/cod-penal'
      fullPath: '/cod-penal'
      preLoaderRoute: typeof CodPenalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumSlug': {
      id: '/forum/$forumSlug'
      path: '/$forumSlug'
      fullPath: '/forum/$forumSlug'
      preLoaderRoute: typeof ForumForumSlugRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum/thread/$threadId': {
      id: '/forum/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/forum/thread/$threadId'
      preLoaderRoute: typeof ForumThreadThreadIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum/new-topic/$forumSlug': {
      id: '/forum/new-topic/$forumSlug'
      path: '/new-topic/$forumSlug'
      fullPath: '/forum/new-topic/$forumSlug'
      preLoaderRoute: typeof ForumNewTopicForumSlugRouteImport
      parentRoute: typeof ForumRoute
    }
  }
}

interface ForumRouteChildren {
  ForumForumSlugRoute: typeof ForumForumSlugRoute
  ForumNewTopicForumSlugRoute: typeof ForumNewTopicForumSlugRoute
  ForumThreadThreadIdRoute: typeof ForumThreadThreadIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumForumSlugRoute: ForumForumSlugRoute,
  ForumNewTopicForumSlugRoute: ForumNewTopicForumSlugRoute,
  ForumThreadThreadIdRoute: ForumThreadThreadIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CodPenalRoute: CodPenalRoute,
  ForumRoute: ForumRouteWithChildren,
  RegulamentRoute: RegulamentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
